### ISSUE TITLE
expected enum `image::dynimage::DynamicImage`, found a different enum `image::dynimage::DynamicImage`

### ISSUE THREAD

**Issue by mantou132** [piderman314/bardecoder#10]
Installed bardecoder as a dependency, but cannot use image library like example.

**Comment by piderman314** [comment]
This sounds like a version mismatch. Do you have the image library as a dependency yourself? If so, what version?

**Comment by mantou132** [comment]
Thank you. The version of `image` I installed is 0.22. Changing to 0.21 will not cause this error.

**Comment by piderman314** [comment]
It's updated to 0.22 on the master branch a while back if you really want to use that version of `image`.
