### ISSUE TITLE
Why does the decode method try to own the source?

### ISSUE THREAD

**Issue by sumibi-yakitori** [piderman314/bardecoder#12]
Why can't I use source borrowing when source is immutable?

https://docs.rs/bardecoder/0.1.2/src/bardecoder/decoder.rs.html#27

**Comment by piderman314** [comment]
I have no idea haha. I think I wrote some code long ago that required it but it seems to work fine as a reference now. I'll make a 0.2 release for this since the interface changed.

**Comment by piderman314** [comment]
Ok version 0.2 is now published. Thanks for the report :) https://crates.io/crates/bardecoder/0.2.0
