### ISSUE TITLE
UTF-8 qrcode

### ISSUE THREAD

**Issue by zinggdavid** [piderman314/bardecoder#15]
The following code produces wrong utf-8 output analyzing the attached image. Any Idea to fix it?

`use bardecoder;
use image;
use std::env;
//use std::io::{self, Write};

fn main() {
    let args: Vec<String> = env::args().collect();
    match args.len() {
        2 => {
            // scanning img
            //println!("scanning: {}", &args[1]);
            let _img = image::open(&args[1]).unwrap();
            let decoder = bardecoder::default_decoder();
            let results = decoder.decode(&_img);
            
            for result in results {
                //let result2: i32 = result.unwrap()
                println!("{}", result.unwrap()); 
                //io::stdout().write_all(str::from_utf8(&result)).unwrap();
                //io::stdout().write_all(result.unwrap().as_bytes()).unwrap();
                //println!("{:?}", result.unwrap().as_bytes());
            }
        }
        _ => {
            println!("Usage: rust-barcode.exe <path\\to\\img>");
        }
    }
}`
![001-erkannt](https://user-images.githubusercontent.com/30095765/79228473-c88f8d80-7e61-11ea-95e4-db638791df2f.jpg)

**Comment by piderman314** [comment]
Hey, I was having a look at this. Your QR code encodes things as "8-bit" data which officially uses the JIS-8 character set. However I guess most people won't use it for Japanese characters ;) I will try to detect the presence of 0xC3 which is usually a good indicator of "western" UTF-8 data.

Having said that, your 8-bit data contains the data point 0xF4 (decimal 244) which does not appear to be valid UTF-8 (this would be the ô in Garôena) So after this change your QR will result in a "cannot convert to UTF-8" error message.

**Comment by zinggdavid** [comment]
Hi piderman, thanks for your answer. We are no experts for qr codes at all but we did some googling and found some articles discussing QR code text encoding. And the concencus in the articles seems that ISO/IEC 8859-1 is the default encoding for "8-bit". We assume that QR codes we are trying to recoginze are encoded in ISO 8859-1. 

For example wikipedia says that 8859-1 is the default encoding for "8-bit":
https://en.wikipedia.org/wiki/QR_code#Encoding
We also found this stackoverflow thread discussing different text encodings wich seems to contain a lot usefull information:
https://stackoverflow.com/questions/51516612/choosing-a-character-encoding-for-qr-codes

We would appreciate a lot if you could look into this as your library works very well for us except for the encoding issue, which is unfortunately a show stopper for us. If we could help in any way, please let us know, but unfortunately we are pretty much beginners with QR codes and rust.
Many thanks in advance.

**Comment by piderman314** [comment]
Ok this should have been fixed. Can you please try version 0.2.2 ?

**Comment by zinggdavid** [comment]
Many thanks, it works fine with version 0.2.2!
