### ISSUE TITLE
Add support for other QR Code versions and ECC modes

### ISSUE THREAD

**Issue by KyleMaas** [piderman314/bardecoder#17]
I'm getting invalid combination errors for versions (20 in any ECC mode, for example) and ECC modes (40 in Quartile).  It would be nice if block_info had a complete set of data for all version numbers and ECC modes.

**Comment by piderman314** [comment]
Yeah it was really boring to add all that data manually so I stopped after a while. I'll see if I can add some more ;)

**Comment by KyleMaas** [comment]
Awesome.  I'd be happy to help with this if I knew how you figure out the numbers the options need.

**Comment by KyleMaas** [comment]
Really, it might be even better if that information could be generated programmatically instead of requiring manual lookup table generation.

**Comment by piderman314** [comment]
I only have a crappy PDF with all the data (the official spec even). But I managed to regex my way through it ;)

**Comment by KyleMaas** [comment]
Awesome!  This was the main thing blocking my other project from moving forward.  Thanks!
