### ISSUE TITLE
Version in README

### ISSUE THREAD

**Issue by justinmoon** [piderman314/bardecoder#30]
You use `bardecoder = "0.3.0"` in your README example.

[But it seems like this version hasn't been published yet on crates.io](https://crates.io/crates/bardecoder)?

**Comment by piderman314** [comment]
Ah you are right, I set it to the master version, but it's more convenient to have it be the last published version.

**Comment by piderman314** [comment]
I changed this a while ago so I need to check what the correct `image` version is for 0.2.2 and then I'll update it.
