### ISSUE TITLE
Did Not Read QR

### ISSUE THREAD

**Issue by Ricotan-naboon** [piderman314/bardecoder#31]
Hey, I'm a Japanese stupid student who has a question.
I tried reading this card QR. (This card is "aikatsu" which famous idol anime in Japan) ![QR](https://user-images.githubusercontent.com/51312671/96533076-28ab3480-12c8-11eb-88da-1f3b9ed63751.png)
but rust return `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QRError { msg: "Format information corrupted" }', src/main.rs:9:31` . I don't know encoding and other QR technical specifications. Please tell me how to fix can read QR.

**Comment by Ricotan-naboon** [comment]
main.rs

```fn main() {
    let img = image::open("QR.png").unwrap();
    let decoder = bardecoder::default_decoder();

    let results = decoder.decode(&img);
    for result in results {
        println!("{}", result.unwrap());
    }
}
```

Cargo.toml

```[package]
name = "XXX"
version = "0.1.0"
authors = ["Ricotan-Naboon <XXXX>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bardecoder = { version = "0.2.2", features = ["debug-images"] }
image = "0.22.5"```

**Comment by piderman314** [comment]
Hi, this is because the image suffers from compression artifacts and a slight blurriness. My algorithm isn't capable enough to deal with it. I ran it through a simple sharpen filter (for example with the Photos editor in Windows); then it was able to be decoded.
