### ISSUE TITLE
Error decoding QR Code: Mode 1101 not yet implemented.

### ISSUE THREAD

**Issue by UnicornsOnLSD** [piderman314/bardecoder#33]
I'm trying to use bardecoder to scan a QR code on a camera. When scanning the QR code, I get the error Mode 1101 not yet implemented". I found the message in src/decode/qr/data.rs, but I can't tell what QR formats are supported.

**Comment by UnicornsOnLSD** [comment]
Here's the QR I'm decoding btw

![Screenshot_1612904102](https://user-images.githubusercontent.com/44349936/107427416-48859300-6b19-11eb-8e62-d8e0308e2747.png)

**Comment by piderman314** [comment]
Hey, thanks for your report. I've had a look and the issue stems from the fact that your image is larger than bardecoder is setup to deal with by default. There are two things you could do:

1) Resize the image before passing it to the library. I've tested it with 25% size and this works. This has the added benefit that the library will be a *lot* faster in processing the image.

2) You can modify the parameters of the library. You can see an example of this in the [Modified](https://github.com/piderman314/bardecoder#modified) section of the README. I was able to decode your image if I set the parameters of BlockedMean to 11, 13. This helps in processing a larger image by looking at larger subsections at a time so it doesn't get confused by only looking at white or black parts.

Please let me know if you require further assistance.

**Comment by UnicornsOnLSD** [comment]
Thanks, this was actually just a screenshot of my QR code, I'm actually holding it up to a camera to scan it. I think my issue was that I was putting too much data in the QR code, causing decoding to mess up. Instead of using json, I'm just sending the values separated by a comma, which greatly reduced size. Thanks for your help :)
