### ISSUE TITLE
Fails to decode rather obvious QR code

### ISSUE THREAD

**Issue by vi** [piderman314/bardecoder#35]
The library, initialized using `bardecoder::default_decoder()` seems to fail to decode rather obvious QR code:

![test](https://user-images.githubusercontent.com/173219/131329136-0e9459d9-362b-4993-a9fd-192dbe9b66ec.png)

`zbarimg` command line tool, for example, does successfully decode this case:

```
$ zbarimg test.png
QR-Code:0216
scanned 1 barcode symbols from 1 images in 0.04 seconds
```

https://crates.io/crates/zbar-rust also succeeds in decoding the image.

**Comment by piderman314** [comment]
Yes, this is because the perspective is not head-on, and my algorithm isn't the best in those cases. I'll see if I can improve it a little bit.

**Comment by vi** [comment]
If the library does not typically scan what can be scanned by a smartphone then README should state limitations and recommended use cases.

**Comment by piderman314** [comment]
This should be improved in version v0.3.0
