### ISSUE TITLE
Is there a convenient way to return the raw bytes of decoding?

### ISSUE THREAD

**Issue by 1ooper** [piderman314/bardecoder#38]

**Comment by piderman314** [comment]
No because it doesn't really make sense. Any QR code's raw bytes are meant to be decoded to text and/or numbers in a specific way. The only thing you could realistically do with the raw bytes is decode it yourself, but I'm not sure why you would want to do that?

**Comment by 1ooper** [comment]
> No because it doesn't really make sense. Any QR code's raw bytes are meant to be decoded to text and/or numbers in a specific way. The only thing you could realistically do with the raw bytes is decode it yourself, but I'm not sure why you would want to do that?

Thank you for your reply. I want a offline device to communicate through QR code. Sometimes, a message _lenth_ is over the capability of QR codes, especially with long _BigInt_ types unless _BigInt_  is converted to raw bytes. That's when I want to the raw bytes of the decoding result.
