### ISSUE TITLE
Is this a mistake/misspell?

### ISSUE THREAD

**Issue by mrg0lden** [piderman314/bardecoder#41]
Hi, I have been going through the source code for a few days, and here I found that `left` and `right` are essentially the same values.
So, I wondered if it should have been something else.

https://github.com/piderman314/bardecoder/blob/a8cbe330fc203660a7ff024b8867f8e04b2ea05a/src/extract/qr/mod.rs#L358

**Comment by piderman314** [comment]
Whoops, that's a typo. Well spotted.

**Comment by mrg0lden** [comment]
Since you have responded, I want to take the chance to ask you about the algorithms used. Is there any reference I can use to better understand what is going on? If not, do you mind giving a brief explanation of how things work?

Thank you.

**Comment by piderman314** [comment]
For the most part I used the information in the QR standard which is available under ISO 18004.
