### ISSUE TITLE
Enable detection of codes with homographic transformations

### ISSUE THREAD

**Issue by stephanemagnenat** [piderman314/bardecoder#48]
Currently, the `QRLocation` only stores the positions of the 3 finder patterns, but not the position of the alignment marking. If it would do so, it would allow the subsequent passes to handle codes seen not frontally, because we could compute a 2-D homography between the visual space and the code space.

@piderman314 would you potentially be open to adding such a field (as an option, as version 1 lacks it)?

At the moment, bardecoder is not able to decode QR codes with perspective transforms, such as these ones:
![qrcode-perspective1](https://github.com/piderman314/bardecoder/assets/390278/332ff510-9f88-4f6c-8bbf-4d564d6e3dbf)
![qrcode-perspective2](https://github.com/piderman314/bardecoder/assets/390278/5aa958b6-4c94-49a5-af5b-5abf2bb0ee67)

This is a problem for AR/vision applications.

**Comment by stephanemagnenat** [comment]
Thank you for the improvement! I think that now it is ok, after some experiments I would go for two QR codes for robustness when looking form homographic transformations.

**Comment by piderman314** [comment]
Excellent. I've published version `0.4.2` for ease of use.
