### ISSUE TITLE
Support for SubImages?

### ISSUE THREAD

**Issue by KyleMaas** [piderman314/bardecoder#49]
The documentation says to keep the source image size small, but the source images I have are huge.  So I tried slicing them up using `DynamicImage::view()`.  However, this results in a type of `SubImage<&DynamicImage>`, which supports the `GenericImage` trait and thus I think it supports everything bardecoder needs.  But I can't seem to find an efficient way to coerce this into something that bardecoder will work on.  I've resorted to essentially this:

```
decoder.decode(&(DynamicImage::ImageRgba8(original_image.view(x, y, w, h).to_image())));
```

...which seems like a really silly thing to have to do.  Is there a better way to do this?

**Comment by piderman314** [comment]
I'll see if I can do something with `GenericImage[View]` but rust is being a bit difficult about passing traits in generic structs.

**Comment by KyleMaas** [comment]
That'd be awesome.  I tried my hand at making my a builder but am still not familiar enough with Rust to be successful at it.

**Comment by piderman314** [comment]
I have implemented a change for this that would allow you to call `decoder.decode(&original_image.view(x, y, w, h).to_image());` . Could you please have a look to see if it works? :)

**Comment by piderman314** [comment]
I think `decoder.decode(&*original_image.view(x, y, w, h));` would also work though I personally prefer the first one.

**Comment by piderman314** [comment]
Also to avoid version conflicts, it is now required to use `image` version `0.24` or newer.

**Comment by KyleMaas** [comment]
That does seem to function as expected.  Thanks!
