### ISSUE TITLE
Out of bounds panic trying to read image chunks

### ISSUE THREAD

**Issue by KyleMaas** [piderman314/bardecoder#50]
When trying to decode data from a portion of an image which is pretty much all barcode data (chunks of a larger image filled with barcodes), I can consistently get the following panic:

```
[2023-07-16T13:51:45Z DEBUG bardecoder::extract::qr] LOC QRLocation { top_left: Point { x: 11.0, y: 6.0 }, top_right: Point { x: 377.0, y: 6.0 }, bottom_left: Point { x: 37.0, y: 346.0 }, module_size: 2.0, version: 40 }
thread 'main' panicked at 'Image index (400, 343) out of bounds (400, 400)', (((directory redacted)))/image-0.24.6/./src/buffer.rs:769:21
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: image::buffer_::ImageBuffer<P,Container>::get_pixel
             at (((directory redacted)))/image-0.24.6/src/buffer.rs:769:21
   3: bardecoder::extract::qr::is_alignment
             at (((directory redacted)))/bardecoder-0.4.2/src/extract/qr/mod.rs:338:12
   4: bardecoder::extract::qr::determine_perspective
             at (((directory redacted)))/bardecoder-0.4.2/src/extract/qr/mod.rs:137:20
   5: <bardecoder::extract::qr::QRExtractor as bardecoder::extract::Extract<image::buffer_::ImageBuffer<image::color::Luma<u8>,alloc::vec::Vec<u8>>,bardecoder::util::qr::QRLocation,bardecoder::util::qr::QRData,bardecoder::util::qr::QRError>>::extract
             at (((directory redacted)))/bardecoder-0.4.2/src/extract/qr/mod.rs:39:17
   6: bardecoder::decoder::Decoder<IMG,PREPD,RESULT>::decode
             at (((directory redacted)))/bardecoder-0.4.2/src/decoder.rs:39:37
(((portion of trace in my code redacted)))
```

It still has the same problem if I create a new image with a small extra blank area around the original image (thinking maybe it was running off into what should be a quiet zone, so synthetically simulating a quiet zone), although it does not happen as frequently.  If I make the blank area around the barcode much larger (about half the size of the barcode itself), it runs just fine.

**Test case 1**
Attempting to generate a test case by going through the same cropping steps my program's doing (I have not tried writing up a recognizer specifically to test these, but they should be the same data my program's crashing on) would yield something like this:

![testcase-1-crash](https://github.com/piderman314/bardecoder/assets/2281400/14708213-18ba-4122-b5b2-0961cae174d0)
(Crashes)

**Test case 2**
Adding a 10px white border around it means it doesn't crash on the earlier image but crashes on a later chunk:
![testcase-2-no-crash](https://github.com/piderman314/bardecoder/assets/2281400/b276cdc0-2ab3-423a-94ec-4c7feb4611c0)
(Doesn't crash)

![testcase-2-crash](https://github.com/piderman314/bardecoder/assets/2281400/cae0bb94-d5f0-4023-9341-1b01e02a388c)
(Crashes)

**Test case 3**
Adding a 100px white border allows it to complete successfully:

![testcase-3-no-crash](https://github.com/piderman314/bardecoder/assets/2281400/37ec8b4c-54dd-40ff-ab72-bc78f22660f5)

**Comment by piderman314** [comment]
Yeah this stems from the fact that you have extra locator patterns (the big squares) in the picture. The library thinks that that the left two locators combined with the one in the upper right might be a QR code. Since finding a QR code starts with a bit of guesswork (there could be false positives) it now guesses out of bounds. I'll see if I can add some extra checks but in general I would advise against having erroneous data so close to the actual data.

**Comment by KyleMaas** [comment]
Thank you for the quick response!

Having enough checks that it doesn't go out of bounds and panic would be perfect.  In this case, the barcodes are already spaced at I think 6 modules from each other, which is more than the spec mandates at 4 modules of quiet zone.  Ideally, more separation would be great, but for this application the minimum separation possible helps quite a bit.

**Comment by KyleMaas** [comment]
It seems the quiet zone needs to be somewhere between 32 (crashes) and 40 (doesn't crash) modules wide to keep from triggering this.

**Comment by piderman314** [comment]
I've fixed the out of bounds checking and the library should now return a valid response. Note that it thinks there are a lot more QRs than there are so you'll have to loop through the results and check which ones are `Ok` and which ones are `Err`. Though in this case they are all `Err` because of the utf8 conversion failure.

**Comment by KyleMaas** [comment]
That works perfectly.  Thank you!

**Comment by piderman314** [comment]
Thanks for the reports, I've published version `0.5.0` with the two fixes.

**Comment by KyleMaas** [comment]
Excellent.  Thanks!

**Comment by KyleMaas** [comment]
By the way, this is the thing I've been working on (in my copious free time) for the last several years which has brought about some of these weird use cases:

https://github.com/KyleMaas/realworldarchive

Finally have it in a state where it's usable enough to publish.

**Comment by piderman314** [comment]
Ah cool. Now I also understand your concern with data density ;)

**Comment by KyleMaas** [comment]
Yeah, the more densely the data can be packed, the fewer printed pages are required for a given input file.  The barcode packing algorithm I'm using right now is nowhere near ideal.  I've got an idea for a way to improve it to better protect against likely damage to printed pages (namely, water/fire damage around the edges) which will also improve packing density significantly, but it's going to take me a while to implement elegantly.  The density issue is also the reason I've been spending so much time experimenting with color multiplexing to try to find the best ways to multiplex and have it carry across from RGB->printed CMYK->scanned RGB and with as few misreads as possible.  So far I'm pretty happy with the way it works, and it should be reasonably easy to reimplement as a compatible system in another language or platform, which is another major goal of the project - open reimplementable standard which can be easily targeted by others.  Since it's so experimental, the code quality's pretty well garbage, but that'll get there eventually.  At any rate, it's been a fun, rewarding, and useful project to work on.
