### ISSUE TITLE
Way to read binary encoding as raw binary?

### ISSUE THREAD

**Issue by KyleMaas** [piderman314/bardecoder#52]
Is there a way to skip the encoding autodetection in the binary mode and just read the raw byte data?

https://github.com/piderman314/bardecoder/blob/e1fcff7f4975c8f9cc430b61b0a0ac29a4b1dd78/src/decode/qr/data.rs#L167-L187

**Comment by piderman314** [comment]
I don't think this is very useful. QR codes are meant to store text and thus even the "binary" mode is intended to store ISO8859-1 or UTF-8. If you really need to have raw binary data I would suggest using something like base64 to convert it into characters.

**Comment by KyleMaas** [comment]
Okay.  Thank you!

**Comment by jerabaul29** [comment]
A note: the need for storing binary data in qr codes is discussed on quite many places on the internet, and several packages support it. See for example the discussion at:

https://stackoverflow.com/questions/60506222/encode-decode-binary-data-in-a-qr-code-using-qrencode-and-zbarimg-in-bash

The maintainers of zbarimg ended up agreeing that supporting binary data is useful, and adding it to zbarimg.

I think that could be a nice feature to have on the roadmap to add in the future :) .
