### ISSUE TITLE
Unable to read this code.

### ISSUE THREAD

**Issue by woolnough** [piderman314/bardecoder#6]
I downloaded a few sample QR codes from the internet to play with. This one failed to decode with error message:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QRError { msg: "Could not calculate error distances" }', src/libcore/result.rs:997:5

 I'm too new to Rust to understand why, sorry!

![qr-code-nbt-e1432209855429](https://user-images.githubusercontent.com/25757544/57178726-31cbfa00-6eb8-11e9-9f7c-1fb2bb13209d.gif)

I was using the "Quick" decode you posted but the sample "Modified" gave the same result.

This website: https://zxing.org was able to decode it successfully.

**Comment by piderman314** [comment]
You are right, something looks to be off in my code. I'll have a look at it later.

**Comment by piderman314** [comment]
I have fixed the issue, the 0.1.1 release should now work for you. Thanks for the report!

https://github.com/piderman314/bardecoder/commit/16fc3bcdde2d294e83da5d90299af46edcdda0cf
